/** Renomeia a tabela **/
RENAME TABLE curso TO TB_CURSO;

/** Renomeia as coluna **/
ALTER TABLE TB_CURSO RENAME COLUMN curso_id TO CURSO_CD;
ALTER TABLE TB_CURSO RENAME COLUMN curso_nome TO CURSO_DESCR;
ALTER TABLE TB_CURSO RENAME COLUMN curso_idEscola TO CURSO_ESCOLA_CD;
ALTER TABLE TB_CURSO RENAME COLUMN curso_idAnoLetivo TO CURSO_ANO_LETIVO_CD;
ALTER TABLE TB_CURSO RENAME COLUMN curso_idModalidadeEnsino TO CURSO_MODALIDADE_ENSINO_CD;
ALTER TABLE TB_CURSO RENAME COLUMN curso_idFormaOrganizacao TO CURSO_ORGANIZACAO_CD;
ALTER TABLE TB_CURSO RENAME COLUMN curso_idSerie TO CURSO_SERIE_CD;
ALTER TABLE TB_CURSO RENAME COLUMN curso_cargaHoraria TO CURSO_CH;
ALTER TABLE TB_CURSO RENAME COLUMN curso_idFormaAvaliacao TO CURSO_AVALIACAO_CD;
ALTER TABLE TB_CURSO RENAME COLUMN curso_idFormaProgressao TO CURSO_PROGRESSAO_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_CURSO ADD COLUMN CURSO_CRIADO_EM datetime;
ALTER TABLE TB_CURSO ADD COLUMN CURSO_ATUALIZADA_EM datetime;
ALTER TABLE TB_CURSO ADD COLUMN CURSO_DELETADO_EM datetime;
