/** Renomeia a tabela **/
RENAME TABLE dados_campus_das_unidades_has_tipo_de_equipamento TO TB_CAMPUS_EQUIP;

/** Renomeia as coluna **/
ALTER TABLE TB_CAMPUS_EQUIP RENAME COLUMN id TO CAMPUS_EQUIP_CD;
ALTER TABLE TB_CAMPUS_EQUIP RENAME COLUMN dados_campus_das_unidades_iddados_campus_das_unidades TO CAMPUS_EQUIP_UNIDADES_CD;
ALTER TABLE TB_CAMPUS_EQUIP RENAME COLUMN tipo_de_equipamento_tipo_de_equipamento_id TO CAMPUS_EQUIP_EQUIPAMENTO_CD;
ALTER TABLE TB_CAMPUS_EQUIP RENAME COLUMN quantidade TO CAMPUS_EQUIP_QTD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_CAMPUS_EQUIP ADD COLUMN CAMPUS_EQUIP_CRIADO_EM datetime;
ALTER TABLE TB_CAMPUS_EQUIP ADD COLUMN CAMPUS_EQUIP_ATUALIZADA_EM datetime;
ALTER TABLE TB_CAMPUS_EQUIP ADD COLUMN CAMPUS_EQUIP_DELETADO_EM datetime;
