/** Renomeia a tabela **/
RENAME TABLE diario_classe TO TB_DIARIO_CLASSE;

/** Renomeia as coluna **/
ALTER TABLE TB_DIARIO_CLASSE RENAME COLUMN iddiario_classe TO DIARIO_CD;
ALTER TABLE TB_DIARIO_CLASSE RENAME COLUMN idestabelecimento_ensino TO DIARIO_ESTABELECIMENTO_CD;
ALTER TABLE TB_DIARIO_CLASSE RENAME COLUMN iddisciplina TO DIARIO_DISCIPLINA_CD;
ALTER TABLE TB_DIARIO_CLASSE RENAME COLUMN data TO DIARIO_DATA;
ALTER TABLE TB_DIARIO_CLASSE RENAME COLUMN idserie TO DIARIO_SERIE_CD;
ALTER TABLE TB_DIARIO_CLASSE RENAME COLUMN idturma TO DIARIO_TURMA_CD;
ALTER TABLE TB_DIARIO_CLASSE RENAME COLUMN idusuario TO DIARIO_USUARIO_CD;
ALTER TABLE TB_DIARIO_CLASSE RENAME COLUMN conteudo TO DIARIO_CONTEUDO;
ALTER TABLE TB_DIARIO_CLASSE RENAME COLUMN indice TO DIARIO_INDICE;
ALTER TABLE TB_DIARIO_CLASSE RENAME COLUMN descricao TO DIARIO_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_DIARIO_CLASSE ADD COLUMN DIARIO_CRIADO_EM datetime;
ALTER TABLE TB_DIARIO_CLASSE ADD COLUMN DIARIO_ATUALIZADA_EM datetime;
ALTER TABLE TB_DIARIO_CLASSE ADD COLUMN DIARIO_DELETADO_EM datetime;
