/** Renomeia a tabela **/
RENAME TABLE documentos TO TB_DOCUMENTOS;

/** Renomeia as coluna **/
ALTER TABLE TB_DOCUMENTOS RENAME COLUMN id TO DOCUMENTOS_CD;
ALTER TABLE TB_DOCUMENTOS RENAME COLUMN identificacao_da_pessoa_id TO DOCUMENTOS_PESSOA_CD;
ALTER TABLE TB_DOCUMENTOS RENAME COLUMN tipo_dados_certidao_id TO DOCUMENTOS_CERTIDAO_CD;
ALTER TABLE TB_DOCUMENTOS RENAME COLUMN cpf TO DOCUMENTOS_CPS;
ALTER TABLE TB_DOCUMENTOS RENAME COLUMN registro_geral_id TO DOCUMENTOS_RG_CD;
ALTER TABLE TB_DOCUMENTOS RENAME COLUMN ctps_id TO DOCUMENTOS_CTPS_CD;
ALTER TABLE TB_DOCUMENTOS RENAME COLUMN titulo_eleitor_id TO DOCUMENTOS_TITULO_ELEITOR_CD;
ALTER TABLE TB_DOCUMENTOS RENAME COLUMN estado_civil TO DOCUMENTOS_ESTADO_CIVIL;
ALTER TABLE TB_DOCUMENTOS RENAME COLUMN email TO DOCUMENTOS_EMAIL;

/** Adiciona as novas colunas **/
ALTER TABLE TB_DOCUMENTOS ADD COLUMN DOCUMENTOS_CRIADO_EM datetime;
ALTER TABLE TB_DOCUMENTOS ADD COLUMN DOCUMENTOS_ATUALIZADA_EM datetime;
ALTER TABLE TB_DOCUMENTOS ADD COLUMN DOCUMENTOS_DELETADO_EM datetime;
