/** Renomeia a tabela **/
RENAME TABLE deficiencia TO TB_DEFICIENCIA;

/** Renomeia as coluna **/
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN id TO DEFICIENCIA_CD;
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN identificacao_da_pessoa_id TO DEFICIENCIA_PESSOA_CD;
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN deficiencia TO DEFICIENCIA_DEFICIENCIA;
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN tipo TO DEFICIENCIA_TIPO;
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN cuidados TO DEFICIENCIA_CUIDADOS;
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN doenca TO DEFICIENCIA_DOENCA;
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN doencas TO DEFICIENCIA_DOENCAS;
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN alergia TO DEFICIENCIA_ALERGIA;
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN alergias TO DEFICIENCIA_ALERGIAS;
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN necessidade TO DEFICIENCIA_NECESSIDADE;
ALTER TABLE TB_DEFICIENCIA RENAME COLUMN necessidades TO DEFICIENCIA_NECESSIDADES;

/** Adiciona as novas colunas **/
ALTER TABLE TB_DEFICIENCIA ADD COLUMN DEFICIENCIA_CRIADO_EM datetime;
ALTER TABLE TB_DEFICIENCIA ADD COLUMN DEFICIENCIA_ATUALIZADA_EM datetime;
ALTER TABLE TB_DEFICIENCIA ADD COLUMN DEFICIENCIA_DELETADO_EM datetime;
