/** Renomeia a tabela **/
RENAME TABLE disciplinas TO TB_DISCIPLINAS;

/** Renomeia as coluna **/
ALTER TABLE TB_DISCIPLINAS RENAME COLUMN disciplina_id TO DISCIPLINAS_CD;
ALTER TABLE TB_DISCIPLINAS RENAME COLUMN ano_letivo_id_ano_letivo TO DISCIPLINAS_ANO_LETIVO_CD;
ALTER TABLE TB_DISCIPLINAS RENAME COLUMN tipo_disciplina_id_tipo_disciplina TO DISCIPLINAS_TIPO_CD;
ALTER TABLE TB_DISCIPLINAS RENAME COLUMN descricao TO DISCIPLINAS_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_DISCIPLINAS ADD COLUMN DISCIPLINAS_CRIADO_EM datetime;
ALTER TABLE TB_DISCIPLINAS ADD COLUMN DISCIPLINAS_ATUALIZADA_EM datetime;
ALTER TABLE TB_DISCIPLINAS ADD COLUMN DISCIPLINAS_DELETADO_EM datetime;
