/** Renomeia a tabela **/
RENAME TABLE definicoes TO TB_DEFINICOES;

/** Renomeia as coluna **/
ALTER TABLE TB_DEFINICOES RENAME COLUMN id TO DEFINICOES_CD;
ALTER TABLE TB_DEFINICOES RENAME COLUMN titulo TO DEFINICOES_TITULO;
ALTER TABLE TB_DEFINICOES RENAME COLUMN descricao TO DEFINICOES_DESCR;
ALTER TABLE TB_DEFINICOES RENAME COLUMN menu TO DEFINICOES_MENU;

/** Adiciona as novas colunas **/
ALTER TABLE TB_DEFINICOES ADD COLUMN DEFINICOES_CRIADO_EM datetime;
ALTER TABLE TB_DEFINICOES ADD COLUMN DEFINICOES_ATUALIZADA_EM datetime;
ALTER TABLE TB_DEFINICOES ADD COLUMN DEFINICOES_DELETADO_EM datetime;
