/** Renomeia a tabela **/
RENAME TABLE despesa_mensal TO TB_DESPESA_MENSAL;

/** Renomeia as coluna **/
ALTER TABLE TB_DESPESA_MENSAL RENAME COLUMN id TO DESPESA_MENSAL_CD;
ALTER TABLE TB_DESPESA_MENSAL RENAME COLUMN energia_eletrica TO DESPESA_MENSAL_ENERGIA;
ALTER TABLE TB_DESPESA_MENSAL RENAME COLUMN aguaEsgoto TO DESPESA_MENSAL_AGUA;
ALTER TABLE TB_DESPESA_MENSAL RENAME COLUMN gas TO DESPESA_MENSAL_GAS;
ALTER TABLE TB_DESPESA_MENSAL RENAME COLUMN alimentacao TO DESPESA_MENSAL_ALIMENTACAO;
ALTER TABLE TB_DESPESA_MENSAL RENAME COLUMN transporte TO DESPESA_MENSAL_TRANSPORTE;
ALTER TABLE TB_DESPESA_MENSAL RENAME COLUMN aluguel TO DESPESA_MENSAL_ALUGUEL;
ALTER TABLE TB_DESPESA_MENSAL RENAME COLUMN medicamentos TO DESPESA_MENSAL_MEDICAMENTOS;

/** Adiciona as novas colunas **/
ALTER TABLE TB_DESPESA_MENSAL ADD COLUMN DESPESA_MENSAL_CRIADO_EM datetime;
ALTER TABLE TB_DESPESA_MENSAL ADD COLUMN DESPESA_MENSAL_ATUALIZADA_EM datetime;
ALTER TABLE TB_DESPESA_MENSAL ADD COLUMN DESPESA_MENSAL_DELETADO_EM datetime;
