/** Renomeia a tabela **/
RENAME TABLE doenca TO TB_DOENCA;

/** Renomeia as coluna **/
ALTER TABLE TB_DOENCA RENAME COLUMN doenca_id TO DOENCA_CD;
ALTER TABLE TB_DOENCA RENAME COLUMN doencaqual TO DOENCA_DESCR;
ALTER TABLE TB_DOENCA RENAME COLUMN necess_especiais_qual TO DOENCA_NECESSIDADES_DESCR;
ALTER TABLE TB_DOENCA RENAME COLUMN necess_especiais TO DOENCA_NECESSIDADES;
ALTER TABLE TB_DOENCA RENAME COLUMN alergicoqual TO DOENCA_ALERGIA_DESCR;
ALTER TABLE TB_DOENCA RENAME COLUMN alergico TO DOENCA_ALERGIA;
ALTER TABLE TB_DOENCA RENAME COLUMN tipodoenca TO DOENCA_TIPO;

/** Adiciona as novas colunas **/
ALTER TABLE TB_DOENCA ADD COLUMN DOENCA_CRIADO_EM datetime;
ALTER TABLE TB_DOENCA ADD COLUMN DOENCA_ATUALIZADA_EM datetime;
ALTER TABLE TB_DOENCA ADD COLUMN DOENCA_DELETADO_EM datetime;
