/** Renomeia a tabela **/
RENAME TABLE dias_semana TO TB_DIAS_SEMANA;

/** Renomeia as coluna **/
ALTER TABLE TB_DIAS_SEMANA RENAME COLUMN dias_semana_id TO DIAS_SEMANA_CD;
ALTER TABLE TB_DIAS_SEMANA RENAME COLUMN descricao TO DIAS_SEMANA_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_DIAS_SEMANA ADD COLUMN DIAS_SEMANA_CRIADO_EM datetime;
ALTER TABLE TB_DIAS_SEMANA ADD COLUMN DIAS_SEMANA_ATUALIZADA_EM datetime;
ALTER TABLE TB_DIAS_SEMANA ADD COLUMN DIAS_SEMANA_DELETADO_EM datetime;
