/** Renomeia a tabela **/
RENAME TABLE endereco_da_familia TO TB_END_FAMILIA;

/** Renomeia as coluna **/
ALTER TABLE TB_END_FAMILIA RENAME COLUMN id TO END_FAMILIA_CD;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN localidade TO END_FAMILIA_LOCALIDADE;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN tipo TO END_FAMILIA_TIPO;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN titulo TO END_FAMILIA_TITULO;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN nome TO END_FAMILIA_NOME;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN numero TO END_FAMILIA_NR;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN complementoNumero TO END_FAMILIA_COMPL;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN complementoAdicional TO END_FAMILIA_COMPL_A;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN cep TO END_FAMILIA_CEP;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN codigoUT TO END_FAMILIA_UT;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN descricaoUT TO END_FAMILIA_UT_DESCR;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN referenciaLocalizacao TO END_FAMILIA_REFERENCIA;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN caracteristicas_do_domicilio_id TO END_FAMILIA_CARACTERISTICA;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN latitude TO END_FAMILIA_LAT;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN longitude TO END_FAMILIA_LONG;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN telefone1 TO END_FAMILIA_TELEFONE1;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN telefone2 TO END_FAMILIA_TELEFONE2;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN estado TO END_FAMILIA_ESTADO;
ALTER TABLE TB_END_FAMILIA RENAME COLUMN cidade TO END_FAMILIA_CIDADE;

/** Adiciona as novas colunas **/
ALTER TABLE TB_END_FAMILIA ADD COLUMN END_FAMILIA_CRIADO_EM datetime;
ALTER TABLE TB_END_FAMILIA ADD COLUMN END_FAMILIA_ATUALIZADA_EM datetime;
ALTER TABLE TB_END_FAMILIA ADD COLUMN END_FAMILIA_DELETADO_EM datetime;
