/** Renomeia a tabela **/
RENAME TABLE evento TO TB_EVENTO;

/** Renomeia as coluna **/
ALTER TABLE TB_EVENTO RENAME COLUMN evento_id TO EVENTO_CD;
ALTER TABLE TB_EVENTO RENAME COLUMN evento_calendarioid TO EVENTO_CALENDARIO_CD;
ALTER TABLE TB_EVENTO RENAME COLUMN evento_tipoid TO EVENTO_TIPO_CD;
ALTER TABLE TB_EVENTO RENAME COLUMN evento_pai TO EVENTO_PAI;
ALTER TABLE TB_EVENTO RENAME COLUMN evento_nome TO EVENTO_NOME;
ALTER TABLE TB_EVENTO RENAME COLUMN evento_dataini TO EVENTO_DT_INI;
ALTER TABLE TB_EVENTO RENAME COLUMN evento_datafim TO EVENTO_DT_FIM;
ALTER TABLE TB_EVENTO RENAME COLUMN evento_link TO EVENTO_LINK;
ALTER TABLE TB_EVENTO RENAME COLUMN evento_descricao TO EVENTO_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_EVENTO ADD COLUMN EVENTO_CRIADO_EM datetime;
ALTER TABLE TB_EVENTO ADD COLUMN EVENTO_ATUALIZADA_EM datetime;
ALTER TABLE TB_EVENTO ADD COLUMN EVENTO_DELETADO_EM datetime;
