/** Renomeia a tabela **/
RENAME TABLE estabelecimento_ensino TO TB_ESTABELECIMENTO;

/** Renomeia as coluna **/
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN idestabelecimento_ensino TO ESTABELECIMENTO_CD;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN nome TO ESTABELECIMENTO_NOME;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN localidade TO ESTABELECIMENTO_LOCALIDADE;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN tipo TO ESTABELECIMENTO_TIPO;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN titulo TO ESTABELECIMENTO_TITULO;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN endereco TO ESTABELECIMENTO_ENDERECO;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN numero TO ESTABELECIMENTO_NR;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN complemento TO ESTABELECIMENTO_COMPLEMENTO;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN cep TO ESTABELECIMENTO_CEP;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN longitude TO ESTABELECIMENTO_LON;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN latitude TO ESTABELECIMENTO_LAT;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN telefone1 TO ESTABELECIMENTO_TELEFONE1;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN telefone2 TO ESTABELECIMENTO_TELEFONE2;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN diretor TO ESTABELECIMENTO_DIRETOR;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN estado TO ESTABELECIMENTO_ESTADO;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN cidade TO ESTABELECIMENTO_CIDADE;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN localizacao TO ESTABELECIMENTO_LOCALIZACAO;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN tipoUnidade TO ESTABELECIMENTO_TIPO_UNIDADE;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN idImportado TO ESTABELECIMENTO_IMPORTADO;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN inep TO ESTABELECIMENTO_INEP;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN decreto TO ESTABELECIMENTO_DECRETO;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN closed TO ESTABELECIMENTO_CLOSED;
ALTER TABLE TB_ESTABELECIMENTO RENAME COLUMN point TO ESTABELECIMENTO_POINT;

/** Adiciona as novas colunas **/
ALTER TABLE TB_ESTABELECIMENTO ADD COLUMN ESTABELECIMENTO_CRIADO_EM datetime;
ALTER TABLE TB_ESTABELECIMENTO ADD COLUMN ESTABELECIMENTO_ATUALIZADA_EM datetime;
ALTER TABLE TB_ESTABELECIMENTO ADD COLUMN ESTABELECIMENTO_DELETADO_EM datetime;
