/** Renomeia a tabela **/
RENAME TABLE escolaridade TO TB_ESCOLARIDADE;

/** Renomeia as coluna **/
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN id TO ESCOLARIDADE_CD;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN identificacao_da_pessoa_id TO ESCOLARIDADE_PESSOA_CD;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN lerEscrever TO ESCOLARIDADE_LER_ESCREVER;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN frequentaEscola TO ESCOLARIDADE_FREQ_ESC;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN nomeEscola TO ESCOLARIDADE_NOME_ESC;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN nesteMunicipio TO ESCOLARIDADE_NESTE_MUNICIPIO;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN estado TO ESCOLARIDADE_ESTADO;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN municipio TO ESCOLARIDADE_MUNICIPIO;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN codigoMec TO ESCOLARIDADE_COD_MEC;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN curso TO ESCOLARIDADE_CURSO_CD;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN anoSerie TO ESCOLARIDADE_ANO_SERIE_CD;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN frequentouCurso TO ESCOLARIDADE_FREQ_CURSO;
ALTER TABLE TB_ESCOLARIDADE RENAME COLUMN ultimoAnoSerie TO ESCOLARIDADE_ULTIMO_ANO_SERIE;

/** Adiciona as novas colunas **/
ALTER TABLE TB_ESCOLARIDADE ADD COLUMN ESCOLARIDADE_CRIADO_EM datetime;
ALTER TABLE TB_ESCOLARIDADE ADD COLUMN ESCOLARIDADE_ATUALIZADA_EM datetime;
ALTER TABLE TB_ESCOLARIDADE ADD COLUMN ESCOLARIDADE_DELETADO_EM datetime;
