/** Renomeia a tabela **/
RENAME TABLE entrevistador TO TB_ENTREVISTADOR;

/** Renomeia as coluna **/
ALTER TABLE TB_ENTREVISTADOR RENAME COLUMN id TO ENTREVISTADOR_CD;
ALTER TABLE TB_ENTREVISTADOR RENAME COLUMN nome TO ENTREVISTADOR_NOME;
ALTER TABLE TB_ENTREVISTADOR RENAME COLUMN cpf TO ENTREVISTADOR_CPF;
ALTER TABLE TB_ENTREVISTADOR RENAME COLUMN assinatura TO ENTREVISTADOR_ASSINATURA;
ALTER TABLE TB_ENTREVISTADOR RENAME COLUMN observacoes TO ENTREVISTADOR_OBSERVACOES;
ALTER TABLE TB_ENTREVISTADOR RENAME COLUMN representante TO ENTREVISTADOR_REPRESENTANTE;

/** Adiciona as novas colunas **/
ALTER TABLE TB_ENTREVISTADOR ADD COLUMN ENTREVISTADOR_CRIADO_EM datetime;
ALTER TABLE TB_ENTREVISTADOR ADD COLUMN ENTREVISTADOR_ATUALIZADA_EM datetime;
ALTER TABLE TB_ENTREVISTADOR ADD COLUMN ENTREVISTADOR_DELETADO_EM datetime;
