/** Renomeia a tabela **/
RENAME TABLE evolucao_biometrica TO TB_EVOLUCAO_BIOMETRICA;

/** Renomeia as coluna **/
ALTER TABLE TB_EVOLUCAO_BIOMETRICA RENAME COLUMN evolucao_biometrica_id TO EVOL_BIO_CD;
ALTER TABLE TB_EVOLUCAO_BIOMETRICA RENAME COLUMN aluno_id_aluno TO EVOL_BIO_ALUNO_CD;
ALTER TABLE TB_EVOLUCAO_BIOMETRICA RENAME COLUMN tipo_evolucao_biometrica_id_tipo_evolucao_biometrica TO EVOL_BIO_TIPO_CD;
ALTER TABLE TB_EVOLUCAO_BIOMETRICA RENAME COLUMN data TO EVOL_BIO_DATA;
ALTER TABLE TB_EVOLUCAO_BIOMETRICA RENAME COLUMN valor TO EVOL_BIO_VALOR;
ALTER TABLE TB_EVOLUCAO_BIOMETRICA RENAME COLUMN observacao TO EVOL_BIO_OBSERVACAO;

/** Adiciona as novas colunas **/
ALTER TABLE TB_EVOLUCAO_BIOMETRICA ADD COLUMN EVOL_BIO_CRIADO_EM datetime;
ALTER TABLE TB_EVOLUCAO_BIOMETRICA ADD COLUMN EVOL_BIO_ATUALIZADA_EM datetime;
ALTER TABLE TB_EVOLUCAO_BIOMETRICA ADD COLUMN EVOL_BIO_DELETADO_EM datetime;
