/** Renomeia a tabela **/
RENAME TABLE forma_organizacao_grupo TO TB_FORMA_ORGANIZACAO;

/** Renomeia as coluna **/
ALTER TABLE TB_FORMA_ORGANIZACAO RENAME COLUMN forma_organizacao_grupo_id TO FORMA_ORG_CD;
ALTER TABLE TB_FORMA_ORGANIZACAO RENAME COLUMN forma_organizacao_grupo_nome TO FORMA_ORG_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_FORMA_ORGANIZACAO ADD COLUMN FORMA_ORG_CRIADO_EM datetime;
ALTER TABLE TB_FORMA_ORGANIZACAO ADD COLUMN FORMA_ORG_ATUALIZADA_EM datetime;
ALTER TABLE TB_FORMA_ORGANIZACAO ADD COLUMN FORMA_ORG_DELETADO_EM datetime;
