/** Renomeia a tabela **/
RENAME TABLE forma_progressao TO TB_FORMA_PROGRESSAO;

/** Renomeia as coluna **/
ALTER TABLE TB_FORMA_PROGRESSAO RENAME COLUMN forma_progressao_id TO FORMA_PROGRESSAO_CD;
ALTER TABLE TB_FORMA_PROGRESSAO RENAME COLUMN forma_progressao_nome TO FORMA_PROGRESSAO_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_FORMA_PROGRESSAO ADD COLUMN FORMA_PROGRESSAO_CRIADO_EM datetime;
ALTER TABLE TB_FORMA_PROGRESSAO ADD COLUMN FORMA_PROGRESSAO_ATUALIZADA_EM datetime;
ALTER TABLE TB_FORMA_PROGRESSAO ADD COLUMN FORMA_PROGRESSAO_DELETADO_EM datetime;
