/** Renomeia a tabela **/
RENAME TABLE forma_avaliacao TO TB_FORMA_AVALIACAO;

/** Renomeia as coluna **/
ALTER TABLE TB_FORMA_AVALIACAO RENAME COLUMN forma_avaliacao_id TO FORMA_AVALIACAO_CD;
ALTER TABLE TB_FORMA_AVALIACAO RENAME COLUMN forma_avaliacao_nome TO FORMA_AVALIACAO_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_FORMA_AVALIACAO ADD COLUMN FORMA_AVALIACAO_CRIADO_EM datetime;
ALTER TABLE TB_FORMA_AVALIACAO ADD COLUMN FORMA_AVALIACAO_ATUALIZADA_EM datetime;
ALTER TABLE TB_FORMA_AVALIACAO ADD COLUMN FORMA_AVALIACAO_DELETADO_EM datetime;
