/** Renomeia a tabela **/
RENAME TABLE falta_docente TO TB_FALTA_DOCENTE;

/** Renomeia as coluna **/
ALTER TABLE TB_FALTA_DOCENTE RENAME COLUMN idFalta_docente TO FALTA_DOCENTE_CD;
ALTER TABLE TB_FALTA_DOCENTE RENAME COLUMN cadastro_servidor_idcadastro_servidor TO FALTA_DOCENTE_SERVIDOR_CD;
ALTER TABLE TB_FALTA_DOCENTE RENAME COLUMN data_Falta_docente TO FALTA_DOCENTE_DATA;
ALTER TABLE TB_FALTA_DOCENTE RENAME COLUMN motivo_Falta_docente TO FALTA_DOCENTE_MOTIVO;

/** Adiciona as novas colunas **/
ALTER TABLE TB_FALTA_DOCENTE ADD COLUMN FALTA_DOCENTE_CRIADO_EM datetime;
ALTER TABLE TB_FALTA_DOCENTE ADD COLUMN FALTA_DOCENTE_ATUALIZADA_EM datetime;
ALTER TABLE TB_FALTA_DOCENTE ADD COLUMN FALTA_DOCENTE_DELETADO_EM datetime;
