/** Renomeia a tabela **/
RENAME TABLE grade_horaria TO TB_GRADE_HORARIA;

/** Renomeia as coluna **/
ALTER TABLE TB_GRADE_HORARIA RENAME COLUMN grade_horaria_id TO GRADE_HORARIA_CD;
ALTER TABLE TB_GRADE_HORARIA RENAME COLUMN grade_horaria_idDisciplina TO GRADE_HORARIA_DISCIPLINA_CD;
ALTER TABLE TB_GRADE_HORARIA RENAME COLUMN grade_horaria_idTurma TO GRADE_HORARIA_TURMA_CD;
ALTER TABLE TB_GRADE_HORARIA RENAME COLUMN grade_horaria_idAula TO GRADE_HORARIA_AULA_CD;
ALTER TABLE TB_GRADE_HORARIA RENAME COLUMN grade_horaria_idDocente TO GRADE_HORARIA_DOCENTE_CD;
ALTER TABLE TB_GRADE_HORARIA RENAME COLUMN grade_horaria_idDiaSemana TO GRADE_HORARIA_DIA_SEMANA_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_GRADE_HORARIA ADD COLUMN GRADE_HORARIA_CRIADO_EM datetime;
ALTER TABLE TB_GRADE_HORARIA ADD COLUMN GRADE_HORARIA_ATUALIZADA_EM datetime;
ALTER TABLE TB_GRADE_HORARIA ADD COLUMN GRADE_HORARIA_DELETADO_EM datetime;
