/** Renomeia a tabela **/
RENAME TABLE hora_fim TO TB_HORA_FIM;

/** Renomeia as coluna **/
ALTER TABLE TB_HORA_FIM RENAME COLUMN hora_fim_id TO HORA_FIM_CD;
ALTER TABLE TB_HORA_FIM RENAME COLUMN descricao TO HORA_FIM_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_HORA_FIM ADD COLUMN HORA_FIM_CRIADO_EM datetime;
ALTER TABLE TB_HORA_FIM ADD COLUMN HORA_FIM_ATUALIZADA_EM datetime;
ALTER TABLE TB_HORA_FIM ADD COLUMN HORA_FIM_DELETADO_EM datetime;
