/** Renomeia a tabela **/
RENAME TABLE historico_saude_aluno TO TB_HISTORICO_SAUDE;

/** Renomeia as coluna **/
ALTER TABLE TB_HISTORICO_SAUDE RENAME COLUMN historico_saude_aluno_id TO HISTORICO_SAUDE_CD;
ALTER TABLE TB_HISTORICO_SAUDE RENAME COLUMN aluno_id_aluno TO HISTORICO_SAUDE_ALUNO_CD;
ALTER TABLE TB_HISTORICO_SAUDE RENAME COLUMN data TO HISTORICO_SAUDE_DATA;
ALTER TABLE TB_HISTORICO_SAUDE RENAME COLUMN evolucao_biometrica TO HISTORICO_SAUDE_EVOLUCAO;
ALTER TABLE TB_HISTORICO_SAUDE RENAME COLUMN doencas_cronicas TO HISTORICO_SAUDE_CRONICAS;
ALTER TABLE TB_HISTORICO_SAUDE RENAME COLUMN alergias TO HISTORICO_SAUDE_ALERGIAS;
ALTER TABLE TB_HISTORICO_SAUDE RENAME COLUMN medicamentos TO HISTORICO_SAUDE_MEDICAMENTOS;
ALTER TABLE TB_HISTORICO_SAUDE RENAME COLUMN necessidades_especiais TO HISTORICO_SAUDE_NECESSIDADES;

/** Adiciona as novas colunas **/
ALTER TABLE TB_HISTORICO_SAUDE ADD COLUMN HISTORICO_SAUDE_CRIADO_EM datetime;
ALTER TABLE TB_HISTORICO_SAUDE ADD COLUMN HISTORICO_SAUDE_ATUALIZADA_EM datetime;
ALTER TABLE TB_HISTORICO_SAUDE ADD COLUMN HISTORICO_SAUDE_DELETADO_EM datetime;
