/** Renomeia a tabela **/
RENAME TABLE historico_deletado TO TB_HISTORICO_DELETADO;

/** Renomeia as coluna **/
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN historico_id TO HISTORICO_DEL_CD;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN aluno_id_aluno TO HISTORICO_DEL_ALUNO_CD;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN series_id_serie TO HISTORICO_DEL_SERIE_CD;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN tipo_matricula_id_matricula TO HISTORICO_DEL_MATRICULA_CD;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN ano_letivo_id_ano TO HISTORICO_DEL_ANO_LETIVO_CD;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN tipo_turno_id_turno TO HISTORICO_DEL_TURNO_CD;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN estabelecimento_ensino_id_estabelecimento TO HISTORICO_DEL_ESTABEL_CD;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN identificacao_unica TO HISTORICO_DEL_IDEN_UNICA;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN aprovado TO HISTORICO_DEL_APROVADO;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN turma TO HISTORICO_DEL_TURMA;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN observacao TO HISTORICO_DEL_OBSERVACAO;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN data TO HISTORICO_DEL_DATA;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN id_tipo_movimento TO HISTORICO_DEL_TIPO_MOV_CD;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN modalidade_ensino TO HISTORICO_DEL_MOD_ENSINO_CD;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN cond_aluno TO HISTORICO_DEL_ALUNO;
ALTER TABLE TB_HISTORICO_DELETADO RENAME COLUMN idOperador TO HISTORICO_DEL_OPERADOR_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_HISTORICO_DELETADO ADD COLUMN HISTORICO_DEL_CRIADO_EM datetime;
ALTER TABLE TB_HISTORICO_DELETADO ADD COLUMN HISTORICO_DEL_ATUALIZADA_EM datetime;
ALTER TABLE TB_HISTORICO_DELETADO ADD COLUMN HISTORICO_DEL_DELETADO_EM datetime;
