/** Renomeia a tabela **/
RENAME TABLE hora_ini TO TB_HORA_INI;

/** Renomeia as coluna **/
ALTER TABLE TB_HORA_INI RENAME COLUMN hora_fim_id TO HORA_INI_CD;
ALTER TABLE TB_HORA_INI RENAME COLUMN descricao TO HORA_INI_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_HORA_INI ADD COLUMN HORA_INI_CRIADO_EM datetime;
ALTER TABLE TB_HORA_INI ADD COLUMN HORA_INI_ATUALIZADA_EM datetime;
ALTER TABLE TB_HORA_INI ADD COLUMN HORA_INI_DELETADO_EM datetime;
