/** Renomeia a tabela **/
RENAME TABLE historico TO TB_HISTORICO;

/** Renomeia as coluna **/
ALTER TABLE TB_HISTORICO RENAME COLUMN historico_id TO HISTORICO_CD;
ALTER TABLE TB_HISTORICO RENAME COLUMN aluno_id_aluno TO HISTORICO_ALUNO_CD;
ALTER TABLE TB_HISTORICO RENAME COLUMN series_id_serie TO HISTORICO_SERIE_CD;
ALTER TABLE TB_HISTORICO RENAME COLUMN tipo_matricula_id_matricula TO HISTORICO_MATRICULA_CD;
ALTER TABLE TB_HISTORICO RENAME COLUMN ano_letivo_id_ano TO HISTORICO_ANO_LETIVO_CD;
ALTER TABLE TB_HISTORICO RENAME COLUMN tipo_turno_id_turno TO HISTORICO_TURNO_CD;
ALTER TABLE TB_HISTORICO RENAME COLUMN estabelecimento_ensino_id_estabelecimento TO HISTORICO_ESTABELECIMENTO_CD;
ALTER TABLE TB_HISTORICO RENAME COLUMN identificacao_unica TO HISTORICO_IDENTIFICACAO_UNICA;
ALTER TABLE TB_HISTORICO RENAME COLUMN aprovado TO HISTORICO_APROVADO;
ALTER TABLE TB_HISTORICO RENAME COLUMN turma TO HISTORICO_TURMA;
ALTER TABLE TB_HISTORICO RENAME COLUMN observacao TO HISTORICO_OBSERVACAO;
ALTER TABLE TB_HISTORICO RENAME COLUMN data TO HISTORICO_DATA;
ALTER TABLE TB_HISTORICO RENAME COLUMN id_tipo_movimento TO HISTORICO_TIPO_MOVIMENTO_CD;
ALTER TABLE TB_HISTORICO RENAME COLUMN modalidade_ensino TO HISTORICO_MODALIDADE_ENSINO_CD;
ALTER TABLE TB_HISTORICO RENAME COLUMN cond_aluno TO HISTORICO_ALUNO;
ALTER TABLE TB_HISTORICO RENAME COLUMN idOperador TO HISTORICO_OPERADOR_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_HISTORICO ADD COLUMN HISTORICO_CRIADO_EM datetime;
ALTER TABLE TB_HISTORICO ADD COLUMN HISTORICO_ATUALIZADA_EM datetime;
ALTER TABLE TB_HISTORICO ADD COLUMN HISTORICO_DELETADO_EM datetime;
