/** Renomeia a tabela **/
RENAME TABLE intervalo TO TB_INTERVALO;

/** Renomeia as coluna **/
ALTER TABLE TB_INTERVALO RENAME COLUMN intervalo_id TO INTERVALO_CD;
ALTER TABLE TB_INTERVALO RENAME COLUMN intervalo_nome TO INTERVALO_DESCR;
ALTER TABLE TB_INTERVALO RENAME COLUMN intervalo_minutos TO INTERVALO_MINUTOS;

/** Adiciona as novas colunas **/
ALTER TABLE TB_INTERVALO ADD COLUMN INTERVALO_CRIADO_EM datetime;
ALTER TABLE TB_INTERVALO ADD COLUMN INTERVALO_ATUALIZADA_EM datetime;
ALTER TABLE TB_INTERVALO ADD COLUMN INTERVALO_DELETADO_EM datetime;
