/** Renomeia a tabela **/
RENAME TABLE indeferidos_telefone TO TB_INDEFERIDOS_TELEFONE;

/** Renomeia as coluna **/
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN historico_id TO INDE_TELEFONE_CD;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN aluno_id_aluno TO INDE_TELEFONE_ALUNO_CD;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN series_id_serie TO INDE_TELEFONE_SERIES_CD;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN tipo_matricula_id_matricula TO INDE_TELEFONE_MATRICULA_CD;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN ano_letivo_id_ano TO INDE_TELEFONE_ANO_LETIVO_CD;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN tipo_turno_id_turno TO INDE_TELEFONE_TURNO_CD;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN estabelecimento_ensino_id_estabelecimento TO INDE_TELEFONE_ESTABELE_CD;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN identificacao_unica TO INDE_TELEFONE_IDENTIFICACAO;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN aprovado TO INDE_TELEFONE_APROVADO;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN turma TO INDE_TELEFONE_TURMA;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN observacao TO INDE_TELEFONE_OBSERVACAO;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN data TO INDE_TELEFONE_DT;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN id_tipo_movimento TO INDE_TELEFONE_TIPO_MOV_CD;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN modalidade_ensino TO INDE_TELEFONE_MOD_ENSINO;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN cond_aluno TO INDE_TELEFONE_COND_ALUNO;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN telefone1 TO INDE_TELEFONE_PRINCIPAL;
ALTER TABLE TB_INDEFERIDOS_TELEFONE RENAME COLUMN telefone2 TO INDE_TELEFONE_SECUNDARIO;

/** Adiciona as novas colunas **/
ALTER TABLE TB_INDEFERIDOS_TELEFONE ADD COLUMN INDE_TELEFONE_CRIADO_EM datetime;
ALTER TABLE TB_INDEFERIDOS_TELEFONE ADD COLUMN INDE_TELEFONE_ATUALIZADA_EM datetime;
ALTER TABLE TB_INDEFERIDOS_TELEFONE ADD COLUMN INDE_TELEFONE_DELETADO_EM datetime;
