/** Renomeia a tabela **/
RENAME TABLE identificacao_da_pessoa TO TB_IDENTIFICACAO_DA_PESSOA;

/** Renomeia as coluna **/
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN id TO IDENT_PES_CD;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN id_familia TO IDENT_PES_FAMILIA_CD;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN ordem TO IDENT_PES_ORDEM;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN nomeCompleto TO IDENT_PES_NOME_COMPLETO;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN identificacao TO IDENT_PES_IDENTIFICACAO;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN apelido TO IDENT_PES_APELIDO;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN sexo TO IDENT_PES_SEXO;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN dataNascimento TO IDENT_PES_DT_NASCIMENTO;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN parentesco TO IDENT_PES_PARENTESCO;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN corRaca TO IDENT_PES_COR_RACA;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN nomeMae TO IDENT_PES_NOME_MAE;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN nomePai TO IDENT_PES_NOME_PAI;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN ondeNasceu TO IDENT_PES_ONDE_NASCEU;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN estado TO IDENT_PES_ESTADO;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN municipio TO IDENT_PES_MUNICIPIO;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN pais TO IDENT_PES_PAIS;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN registroCartorio TO IDENT_PES_REGISTRO_CARTORIO;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN id_aluno TO IDENT_PES_ALUNO_CD;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN nis TO IDENT_PES_NIS;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA RENAME COLUMN log_idUser TO IDENT_PES_LOG_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA ADD COLUMN IDENT_CTRL_CRIADO_EM datetime;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA ADD COLUMN IDENT_CTRL_ATUALIZADA_EM datetime;
ALTER TABLE TB_IDENTIFICACAO_DA_PESSOA ADD COLUMN IDENT_CTRL_DELETADO_EM datetime;
