/** Renomeia a tabela **/
RENAME TABLE localizacao TO TB_LOCALIZACAO;

/** Renomeia as coluna **/
ALTER TABLE TB_LOCALIZACAO RENAME COLUMN idlocalizacao TO LOCALIZACAO_CD;
ALTER TABLE TB_LOCALIZACAO RENAME COLUMN descricao TO LOCALIZACAO_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_LOCALIZACAO ADD COLUMN LOCALIZACAO_CRIADO_EM datetime;
ALTER TABLE TB_LOCALIZACAO ADD COLUMN LOCALIZACAO_ATUALIZADA_EM datetime;
ALTER TABLE TB_LOCALIZACAO ADD COLUMN LOCALIZACAO_DELETADO_EM datetime;
