/** Renomeia a tabela **/
RENAME TABLE logImportacao TO TB_LOG_IMPORTACAO;

/** Renomeia as coluna **/
ALTER TABLE TB_LOG_IMPORTACAO RENAME COLUMN id TO LOG_IMPORTACAO_CD;
ALTER TABLE TB_LOG_IMPORTACAO RENAME COLUMN descricao TO LOG_IMPORTACAO_DESCR;
ALTER TABLE TB_LOG_IMPORTACAO RENAME COLUMN id_aluno TO LOG_IMPORTACAO_ALUNO_CD;
ALTER TABLE TB_LOG_IMPORTACAO RENAME COLUMN id_controle TO LOG_IMPORTACAO_CONTROLE_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_LOG_IMPORTACAO ADD COLUMN LOG_IMPORTACAO_CRIADO_EM datetime;
ALTER TABLE TB_LOG_IMPORTACAO ADD COLUMN LOG_IMPORTACAO_ATUALIZADA_EM datetime;
ALTER TABLE TB_LOG_IMPORTACAO ADD COLUMN LOG_IMPORTACAO_DELETADO_EM datetime;
