/** Renomeia a tabela **/
RENAME TABLE movimentacao_servidor TO TB_MOVIMENTACAO_SERVIDOR;

/** Renomeia as coluna **/
ALTER TABLE TB_MOVIMENTACAO_SERVIDOR RENAME COLUMN idmovimentacao_servidor TO MOV_SERVIDOR_CD;
ALTER TABLE TB_MOVIMENTACAO_SERVIDOR RENAME COLUMN data_movimentacao_servidor TO MOV_SERVIDOR_DT;
ALTER TABLE TB_MOVIMENTACAO_SERVIDOR RENAME COLUMN motivo_movimentacao_servidor TO MOV_SERVIDOR_MOTIVO;
ALTER TABLE TB_MOVIMENTACAO_SERVIDOR RENAME COLUMN cadastro_servidor_idcadastro_servidor TO MOV_SERVIDOR_CAD_SERVIDOR_CD;
ALTER TABLE TB_MOVIMENTACAO_SERVIDOR RENAME COLUMN tipo_movimentacao_servidor_idtipo_movimentacao_servidor TO MOV_SERVIDOR_TIPO_CD;
ALTER TABLE TB_MOVIMENTACAO_SERVIDOR RENAME COLUMN local_idLocal TO MOV_SERVIDOR_LOCAL_CD;
ALTER TABLE TB_MOVIMENTACAO_SERVIDOR RENAME COLUMN cargo TO MOV_SERVIDOR_CARGO_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_MOVIMENTACAO_SERVIDOR ADD COLUMN MOV_SERVIDOR_CRIADO_EM datetime;
ALTER TABLE TB_MOVIMENTACAO_SERVIDOR ADD COLUMN MOV_SERVIDOR_ATUALIZADA_EM datetime;
ALTER TABLE TB_MOVIMENTACAO_SERVIDOR ADD COLUMN MOV_SERVIDOR_DELETADO_EM datetime;
