/** Renomeia a tabela **/
RENAME TABLE movimento_atividade_aluno TO TB_MOVIMENTO_ATIVIDADE_ALUNO;

/** Renomeia as coluna **/
ALTER TABLE TB_MOVIMENTO_ATIVIDADE_ALUNO RENAME COLUMN movimento_atividade_aluno_id TO ATI_ALUNO_CD;
ALTER TABLE TB_MOVIMENTO_ATIVIDADE_ALUNO RENAME COLUMN historico_historico_id TO ATI_ALUNO_HISTORICO_CD;
ALTER TABLE TB_MOVIMENTO_ATIVIDADE_ALUNO RENAME COLUMN tipo_atividade_id_tipo_atividade TO ATI_ALUNO_ATIVIDADE_CD;
ALTER TABLE TB_MOVIMENTO_ATIVIDADE_ALUNO RENAME COLUMN data TO ATI_ALUNO_DT;
ALTER TABLE TB_MOVIMENTO_ATIVIDADE_ALUNO RENAME COLUMN descricao TO ATI_ALUNO_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_MOVIMENTO_ATIVIDADE_ALUNO ADD COLUMN ATI_ALUNO_CRIADO_EM datetime;
ALTER TABLE TB_MOVIMENTO_ATIVIDADE_ALUNO ADD COLUMN ATI_ALUNO_ATUALIZADA_EM datetime;
ALTER TABLE TB_MOVIMENTO_ATIVIDADE_ALUNO ADD COLUMN ATI_ALUNO_DELETADO_EM datetime;
