/** Renomeia a tabela **/
RENAME TABLE medicamento_doenca TO TB_MEDICAMENTO_DOENCA;

/** Renomeia as coluna **/
ALTER TABLE TB_MEDICAMENTO_DOENCA RENAME COLUMN medicamento_doenca_id TO MED_DOENCA_CD;
ALTER TABLE TB_MEDICAMENTO_DOENCA RENAME COLUMN aluno_id_aluno TO MED_DOENCA_ALUNO_CD;
ALTER TABLE TB_MEDICAMENTO_DOENCA RENAME COLUMN doenca_id_doenca TO MED_DOENCA_DOENCA_CD;
ALTER TABLE TB_MEDICAMENTO_DOENCA RENAME COLUMN tipo_doenca_id_tipo_doenca TO MED_DOENCA_TP_DOENCA_CD;
ALTER TABLE TB_MEDICAMENTO_DOENCA RENAME COLUMN O_que_medicar_em_ocorrencias TO MED_DOENCA_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_MEDICAMENTO_DOENCA ADD COLUMN MED_DOENCA_CRIADO_EM datetime;
ALTER TABLE TB_MEDICAMENTO_DOENCA ADD COLUMN MED_DOENCA_ATUALIZADA_EM datetime;
ALTER TABLE TB_MEDICAMENTO_DOENCA ADD COLUMN MED_DOENCA_DELETADO_EM datetime;
