/** Renomeia a tabela **/
RENAME TABLE notas TO TB_NOTAS;

/** Renomeia as coluna **/
ALTER TABLE TB_NOTAS RENAME COLUMN notas_id TO NOTAS_CD;
ALTER TABLE TB_NOTAS RENAME COLUMN historico_id_historico TO NOTAS_HISTORICO_CD;
ALTER TABLE TB_NOTAS RENAME COLUMN disciplina_id_disciplina TO NOTAS_DISCIPLINA_CD;
ALTER TABLE TB_NOTAS RENAME COLUMN observacao TO NOTAS_OBSERVACAO;
ALTER TABLE TB_NOTAS RENAME COLUMN tipo_avaliacao_id_tipo_avaliacao TO NOTAS_AVALIACAO_CD;
ALTER TABLE TB_NOTAS RENAME COLUMN periodo_nota_id_periodo_nota TO NOTAS_PERIODO_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_NOTAS ADD COLUMN NOTAS_CRIADO_EM datetime;
ALTER TABLE TB_NOTAS ADD COLUMN NOTAS_ATUALIZADA_EM datetime;
ALTER TABLE TB_NOTAS ADD COLUMN NOTAS_DELETADO_EM datetime;
