/** Renomeia a tabela **/
RENAME TABLE nomeacao TO TB_NOMEACAO;

/** Renomeia as coluna **/
ALTER TABLE TB_NOMEACAO RENAME COLUMN nomeacao_id TO NOMEACAO_CD;
ALTER TABLE TB_NOMEACAO RENAME COLUMN cadastro_servidor_idcadastro_servidor TO NOMEACAO_SERVIDOR_CD;
ALTER TABLE TB_NOMEACAO RENAME COLUMN id_unidade_nomeacao TO NOMEACAO_UNIDADE_CD;
ALTER TABLE TB_NOMEACAO RENAME COLUMN cargo_nomeacao TO NOMEACAO_CARGO;
ALTER TABLE TB_NOMEACAO RENAME COLUMN data_nomeacao TO NOMEACAO_DT;
ALTER TABLE TB_NOMEACAO RENAME COLUMN descricao_nomeacao TO NOMEACAO_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_NOMEACAO ADD COLUMN NOMEACAO_CRIADO_EM datetime;
ALTER TABLE TB_NOMEACAO ADD COLUMN NOMEACAO_ATUALIZADA_EM datetime;
ALTER TABLE TB_NOMEACAO ADD COLUMN NOMEACAO_DELETADO_EM datetime;
