/** Renomeia a tabela **/
RENAME TABLE ocorrencias_aluno TO TB_OCORRENCIAS_ALUNO;

/** Renomeia as coluna **/
ALTER TABLE TB_OCORRENCIAS_ALUNO RENAME COLUMN idocorrencias_aluno TO OCOR_ALUNO_CD;
ALTER TABLE TB_OCORRENCIAS_ALUNO RENAME COLUMN descr_ocorrencias_aluno TO OCOR_ALUNO_DESCR;
ALTER TABLE TB_OCORRENCIAS_ALUNO RENAME COLUMN data_ocorrencias_aluno TO OCOR_ALUNO_DT;
ALTER TABLE TB_OCORRENCIAS_ALUNO RENAME COLUMN alunos_id_aluno TO OCOR_ALUNO_ALUNOS_CD;
ALTER TABLE TB_OCORRENCIAS_ALUNO RENAME COLUMN enviou_comunicado TO OCOR_ALUNO_COMUNICADO;

/** Adiciona as novas colunas **/
ALTER TABLE TB_OCORRENCIAS_ALUNO ADD COLUMN OCOR_ALUNO_CRIADO_EM datetime;
ALTER TABLE TB_OCORRENCIAS_ALUNO ADD COLUMN OCOR_ALUNO_ATUALIZADA_EM datetime;
ALTER TABLE TB_OCORRENCIAS_ALUNO ADD COLUMN OCOR_ALUNO_DELETADO_EM datetime;
