/** Renomeia a tabela **/
RENAME TABLE ocorrencias_de_saude TO TB_OCORRENCIAS_SAUDE;

/** Renomeia as coluna **/
ALTER TABLE TB_OCORRENCIAS_SAUDE RENAME COLUMN ocorrencias_de_saude_id TO OCOR_SAUDE_CD;
ALTER TABLE TB_OCORRENCIAS_SAUDE RENAME COLUMN aluno_id_aluno TO OCOR_SAUDE_ALUNO_CD;
ALTER TABLE TB_OCORRENCIAS_SAUDE RENAME COLUMN doenca_id_doenca TO OCOR_SAUDE_DOENCA_CD;
ALTER TABLE TB_OCORRENCIAS_SAUDE RENAME COLUMN doenca TO OCOR_SAUDE_DOENCA_DESCR;
ALTER TABLE TB_OCORRENCIAS_SAUDE RENAME COLUMN data TO OCOR_SAUDE_DT;
ALTER TABLE TB_OCORRENCIAS_SAUDE RENAME COLUMN descricao TO OCOR_SAUDE_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_OCORRENCIAS_SAUDE ADD COLUMN OCOR_SAUDE_CRIADO_EM datetime;
ALTER TABLE TB_OCORRENCIAS_SAUDE ADD COLUMN OCOR_SAUDE_ATUALIZADA_EM datetime;
ALTER TABLE TB_OCORRENCIAS_SAUDE ADD COLUMN OCOR_SAUDE_DELETADO_EM datetime;
