/** Renomeia a tabela **/
RENAME TABLE pessoas_internada TO TB_PESSOA_INTERNADA;

/** Renomeia as coluna **/
ALTER TABLE TB_PESSOA_INTERNADA RENAME COLUMN id TO PESSOA_INTERNADA_CD;
ALTER TABLE TB_PESSOA_INTERNADA RENAME COLUMN crianca TO PESSOA_INTERNADA_CRIANCA;
ALTER TABLE TB_PESSOA_INTERNADA RENAME COLUMN adultos TO PESSOA_INTERNADA_ADULTOS;
ALTER TABLE TB_PESSOA_INTERNADA RENAME COLUMN idosos TO PESSOA_INTERNADA_IDOSOS;

/** Adiciona as novas colunas **/
ALTER TABLE TB_PESSOA_INTERNADA ADD COLUMN PESSOA_INTERNADA_CRIADO_EM datetime;
ALTER TABLE TB_PESSOA_INTERNADA ADD COLUMN PESSOA_INTERNADA_ATUALIZADA_EM datetime;
ALTER TABLE TB_PESSOA_INTERNADA ADD COLUMN PESSOA_INTERNADA_DELETADO_EM datetime;
