/** Renomeia a tabela **/
RENAME TABLE prematricula TO TB_PREMATRICULA;

/** Renomeia as coluna **/
ALTER TABLE TB_PREMATRICULA RENAME COLUMN historico_id TO PREMATRICULA_CD;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN aluno_id_aluno TO PREMATRICULA_ALUNO_CD;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN series_id_serie TO PREMATRICULA_SERIE_CD;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN tipo_matricula_id_matricula TO PREMATRICULA_MATRICULA_CD;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN ano_letivo_id_ano TO PREMATRICULA_ANO_LETIVO_CD;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN tipo_turno_id_turno TO PREMATRICULA_TURNO_CD;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN estabelecimento_ensino_id_estabelecimento TO PREMATRICULA_ESTABELE_CD;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN identificacao_unica TO PREMATRICULA_IDENTIFICACAO;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN aprovado TO PREMATRICULA_APROVADO;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN turma TO PREMATRICULA_TURMA;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN observacao TO PREMATRICULA_OBSERVACAO;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN data TO PREMATRICULA_DT;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN id_tipo_movimento TO PREMATRICULA_TIPO_MOV_CD;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN modalidade_ensino TO PREMATRICULA_MOD_ENSINO_CD;
ALTER TABLE TB_PREMATRICULA RENAME COLUMN cond_aluno TO PREMATRICULA_COND_ALUNO;

/** Adiciona as novas colunas **/
ALTER TABLE TB_PREMATRICULA ADD COLUMN PREMATRICULA_CRIADO_EM datetime;
ALTER TABLE TB_PREMATRICULA ADD COLUMN PREMATRICULA_ATUALIZADA_EM datetime;
ALTER TABLE TB_PREMATRICULA ADD COLUMN PREMATRICULA_DELETADO_EM datetime;
