/** Renomeia a tabela **/
RENAME TABLE periodo_nota TO TB_PERIODO_NOTA;

/** Renomeia as coluna **/
ALTER TABLE TB_PERIODO_NOTA RENAME COLUMN periodo_nota_id TO PERIODO_NOTA_CD;
ALTER TABLE TB_PERIODO_NOTA RENAME COLUMN descricao TO PERIODO_NOTA_DESCR;
ALTER TABLE TB_PERIODO_NOTA RENAME COLUMN data_ini TO PERIODO_NOTA_DT_INI;
ALTER TABLE TB_PERIODO_NOTA RENAME COLUMN data_fim TO PERIODO_NOTA_DT_FIM;
ALTER TABLE TB_PERIODO_NOTA RENAME COLUMN dias_letivos TO PERIODO_NOTA_DIAS_LETIVOS;
ALTER TABLE TB_PERIODO_NOTA RENAME COLUMN dias_letivos_art_edfisica TO PERIODO_NOTA_DIAS_EDFISICA;
ALTER TABLE TB_PERIODO_NOTA RENAME COLUMN id_ano_letivo TO PERIODO_NOTA_ANO_LETIVO_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_PERIODO_NOTA ADD COLUMN PERIODO_NOTA_CRIADO_EM datetime;
ALTER TABLE TB_PERIODO_NOTA ADD COLUMN PERIODO_NOTA_ATUALIZADA_EM datetime;
ALTER TABLE TB_PERIODO_NOTA ADD COLUMN PERIODO_NOTA_DELETADO_EM datetime;
