/** Renomeia a tabela **/
RENAME TABLE pedido_transferencia TO TB_PEDIDO_TRANSFERENCIA;

/** Renomeia as coluna **/
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN historico_id TO PEDIDO_TRANS_CD;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN aluno_id_aluno TO PEDIDO_TRANS_ALUNO_CD;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN series_id_serie TO PEDIDO_TRANS_SERIES_CD;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN tipo_matricula_id_matricula TO PEDIDO_TRANS_MATRICULA_CD;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN ano_letivo_id_ano TO PEDIDO_TRANS_ANO_LETIVO_CD;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN tipo_turno_id_turno TO PEDIDO_TRANS_TURNO_CD;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN estabelecimento_ensino_id_estabelecimento TO PEDIDO_TRANS_ESTABELECIMENTO_CD;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN identificacao_unica TO PEDIDO_TRANS_IDENTIFICACAO;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN aprovado TO PEDIDO_TRANS_APROVADO;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN turma TO PEDIDO_TRANS_TURMA;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN observacao TO PEDIDO_TRANS_OBSERVACAO;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN data TO PEDIDO_TRANS_DT;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN id_tipo_movimento TO PEDIDO_TRANS_TIPO_MOVIMENTO_CD;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN modalidade_ensino TO PEDIDO_TRANS_MOD_ENSINO;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA RENAME COLUMN cond_aluno TO PEDIDO_TRANS_COND_ALUNO;

/** Adiciona as novas colunas **/
ALTER TABLE TB_PEDIDO_TRANSFERENCIA ADD COLUMN PEDIDO_TRANS_CRIADO_EM datetime;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA ADD COLUMN PEDIDO_TRANS_ATUALIZADA_EM datetime;
ALTER TABLE TB_PEDIDO_TRANSFERENCIA ADD COLUMN PEDIDO_TRANS_DELETADO_EM datetime;
