/** Renomeia a tabela **/
RENAME TABLE series TO TB_SERIES;

/** Renomeia as coluna **/
ALTER TABLE TB_SERIES RENAME COLUMN id_serie TO SERIES_CD;
ALTER TABLE TB_SERIES RENAME COLUMN serie TO SERIES_SERIE;
ALTER TABLE TB_SERIES RENAME COLUMN desc_serie TO SERIES_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_SERIES ADD COLUMN SERIES_CRIADO_EM datetime;
ALTER TABLE TB_SERIES ADD COLUMN SERIES_ATUALIZADA_EM datetime;
ALTER TABLE TB_SERIES ADD COLUMN SERIES_DELETADO_EM datetime;
