/** Renomeia a tabela **/
RENAME TABLE SerieDocente TO TB_SERIE_DOCENTE;

/** Renomeia as coluna **/
ALTER TABLE TB_SERIE_DOCENTE RENAME COLUMN idserie_por_docente TO SERIE_DOCENTE_CD;
ALTER TABLE TB_SERIE_DOCENTE RENAME COLUMN cadastro_servidor_idcadastro_servidor1 TO SERIE_DOCENTE_CAD_SERVIDOR_CD;
ALTER TABLE TB_SERIE_DOCENTE RENAME COLUMN serieId TO SERIE_DOCENTE_SERIE_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_SERIE_DOCENTE ADD COLUMN SERIE_DOCENTE_CRIADO_EM datetime;
ALTER TABLE TB_SERIE_DOCENTE ADD COLUMN SERIE_DOCENTE_ATUALIZADA_EM datetime;
ALTER TABLE TB_SERIE_DOCENTE ADD COLUMN SERIE_DOCENTE_DELETADO_EM datetime;
