/** Renomeia a tabela **/
RENAME TABLE solicitacao_vinculo_aluno TO TB_SOLICITACAO_VINCULO_ALUNO;

/** Renomeia as coluna **/
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO RENAME COLUMN id_solicitacao TO SOLI_VINCULO_CD;
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO RENAME COLUMN id_usuario TO SOLI_VINCULO_USUARIO_CD;
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO RENAME COLUMN id_historico_aluno TO SOLI_VINCULO_ALUNO_CD;
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO RENAME COLUMN id_escola TO SOLI_VINCULO_ESCOLA_CD;
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO RENAME COLUMN data_solicitacao TO SOLI_VINCULO_DT;
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO RENAME COLUMN aprovado TO SOLI_VINCULO_APROVADO;
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO RENAME COLUMN data_aprovado TO SOLI_VINCULO_DT_APROVADO;
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO RENAME COLUMN id_usuario_aprovacao TO SOLI_VINCULO_USUARIO_APRO_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO ADD COLUMN SOLI_VINCULO_CRIADO_EM datetime;
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO ADD COLUMN SOLI_VINCULO_ATUALIZADA_EM datetime;
ALTER TABLE TB_SOLICITACAO_VINCULO_ALUNO ADD COLUMN SOLI_VINCULO_DELETADO_EM datetime;
