/** Renomeia a tabela **/
RENAME TABLE tipo_de_local TO TB_TIPO_LOCAL;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_LOCAL RENAME COLUMN tipo_de_local_id TO TP_LOCAL_CD;
ALTER TABLE TB_TIPO_LOCAL RENAME COLUMN descricao TO TP_LOCAL_DESC;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_LOCAL ADD COLUMN TP_LOCAL_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_LOCAL ADD COLUMN TP_LOCAL_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_LOCAL ADD COLUMN TP_LOCAL_DELETADO_EM datetime;
