/** Renomeia a tabela **/
RENAME TABLE tipo_de_unidade TO TB_TIPO_UNIDADE;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_UNIDADE RENAME COLUMN idtipo_de_unidade TO TIPO_UNIDADE_CD;
ALTER TABLE TB_TIPO_UNIDADE RENAME COLUMN descricao TO TIPO_UNIDADE_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_UNIDADE ADD COLUMN TIPO_UNIDADE_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_UNIDADE ADD COLUMN TIPO_UNIDADE_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_UNIDADE ADD COLUMN TIPO_UNIDADE_DELETADO_EM datetime;
