/** Renomeia a tabela **/
RENAME TABLE tipo_de_mantenedoras TO TB_TIPO_MANTENEDORA;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_MANTENEDORA RENAME COLUMN tipo_de_mantenedoras_id TO TP_MANTENE_CD;
ALTER TABLE TB_TIPO_MANTENEDORA RENAME COLUMN descricao TO TP_MANTENE_DESC;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_MANTENEDORA ADD COLUMN TP_MANTENE_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_MANTENEDORA ADD COLUMN TP_MANTENE_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_MANTENEDORA ADD COLUMN TP_MANTENE_DELETADO_EM datetime;
