/** Renomeia a tabela **/
RENAME TABLE turma TO TB_TURMA;

/** Renomeia as coluna **/
ALTER TABLE TB_TURMA RENAME COLUMN turma_id TO TURMA_CD;
ALTER TABLE TB_TURMA RENAME COLUMN turma_nome TO TURMA_DESCR;
ALTER TABLE TB_TURMA RENAME COLUMN turma_idCurso TO TURMA_CURSO;
ALTER TABLE TB_TURMA RENAME COLUMN turma_idSala TO TURMA_SALA;
ALTER TABLE TB_TURMA RENAME COLUMN turma_idTurno TO TURMA_TURNO;
ALTER TABLE TB_TURMA RENAME COLUMN closed TO TURMA_FECHADA;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TURMA ADD COLUMN TURMA_CRIADO_EM datetime;
ALTER TABLE TB_TURMA ADD COLUMN TURMA_ATUALIZADA_EM datetime;
ALTER TABLE TB_TURMA ADD COLUMN TURMA_DELETADO_EM datetime;
