/** Renomeia a tabela **/
RENAME TABLE tipo_disciplina TO TB_TIPO_DISCIPLINA;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_DISCIPLINA RENAME COLUMN tipo_disciplina_id TO TP_DIS_CD;
ALTER TABLE TB_TIPO_DISCIPLINA RENAME COLUMN descricao TO TP_DIS_DESC;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_DISCIPLINA ADD COLUMN TP_DIS_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_DISCIPLINA ADD COLUMN TP_DIS_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_DISCIPLINA ADD COLUMN TP_DIS_DELETADO_EM datetime;
