/** Renomeia a tabela **/
RENAME TABLE tipo_de_equipamento TO TB_TIPO_EQUIPAMENTO;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_EQUIPAMENTO RENAME COLUMN tipo_de_equipamento_id TO TP_EQUIP_CD;
ALTER TABLE TB_TIPO_EQUIPAMENTO RENAME COLUMN descricao TO TP_EQUIP_DESC;
ALTER TABLE TB_TIPO_EQUIPAMENTO RENAME COLUMN tipo_dependencia_unidade_id TO TP_EQUIP_UNIDADE;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_EQUIPAMENTO ADD COLUMN TP_EQUIP_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_EQUIPAMENTO ADD COLUMN TP_EQUIP_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_EQUIPAMENTO ADD COLUMN TP_EQUIP_DELETADO_EM datetime;
