/** Renomeia a tabela **/
RENAME TABLE tipo_de_construcao TO TB_TIPO_CONSTRUCAO;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_CONSTRUCAO RENAME COLUMN tipo_de_construcao_id TO TP_CONSTI_CD;
ALTER TABLE TB_TIPO_CONSTRUCAO RENAME COLUMN descricao TO TP_CONST_DESC;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_CONSTRUCAO ADD COLUMN TP_CONST_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_CONSTRUCAO ADD COLUMN TP_CONST_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_CONSTRUCAO ADD COLUMN TP_CONSTL_DELETADO_EM datetime;
