/** Renomeia a tabela **/
RENAME TABLE tipo_evento TO TB_TIPO_EVENTO;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_EVENTO RENAME COLUMN tipo_evento_id TO TP_EVENT_CD;
ALTER TABLE TB_TIPO_EVENTO RENAME COLUMN tipo_evento_descricao TO TP_EVENT_DESC;
ALTER TABLE TB_TIPO_EVENTO RENAME COLUMN tipo_evento_cor TO TP_EVENT_COR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_EVENTO ADD COLUMN TP_EVENT_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_EVENTO ADD COLUMN TP_EVENT_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_EVENTO ADD COLUMN TP_EVENT_DELETADO_EM datetime;
