/** Renomeia a tabela **/
RENAME TABLE tipo_evolucao_biometrica TO TB_TIPO_EVOLUCAO_BIOMETRICA;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_EVOLUCAO_BIOMETRICA RENAME COLUMN tipo_evolucao_biometrica_id TO TP_EVOL_BIO_CD;
ALTER TABLE TB_TIPO_EVOLUCAO_BIOMETRICA RENAME COLUMN descricao TO TP_EVOL_BIO_DESC;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_EVOLUCAO_BIOMETRICA ADD COLUMN TP_EVOL_BIO_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_EVOLUCAO_BIOMETRICA ADD COLUMN TP_EVOL_BIO_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_EVOLUCAO_BIOMETRICA ADD COLUMN TP_EVOL_BIO_DELETADO_EM datetime;
