/** Renomeia a tabela **/
RENAME TABLE tipo_turno TO TB_TIPO_TURNO;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_TURNO RENAME COLUMN tipo_turno_id TO TP_TURNO_CD;
ALTER TABLE TB_TIPO_TURNO RENAME COLUMN descricao TO TP_TURNO_DESC;
ALTER TABLE TB_TIPO_TURNO RENAME COLUMN quantidade_aula TO TP_TURNO_QTD_AULA;
ALTER TABLE TB_TIPO_TURNO RENAME COLUMN quantidade_intervalo TO TP_TURNO_QTD_INTERVALO;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_TURNO ADD COLUMN TP_TURNO_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_TURNO ADD COLUMN TP_TURNO_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_TURNO ADD COLUMN TP_TURNO_DELETADO_EM datetime;
