/** Renomeia a tabela **/
RENAME TABLE tipo_controle_movimentacao_matricula TO TB_TIPO_MOVIMENTACAO_MATRICULA;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_MOVIMENTACAO_MATRICULA RENAME COLUMN tipo_de_construcao_id TO TP_MOV_MAT_CD;
ALTER TABLE TB_TIPO_MOVIMENTACAO_MATRICULA RENAME COLUMN descricao TO TP_MOV_MAT_DESC;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_MOVIMENTACAO_MATRICULA ADD COLUMN TP_MOV_MAT_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_MOVIMENTACAO_MATRICULA ADD COLUMN TP_MOV_MAT_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_MOVIMENTACAO_MATRICULA ADD COLUMN TP_MOV_MAT_DELETADO_EM datetime;
