/** Renomeia a tabela **/
RENAME TABLE trabalho TO TB_TRABALHO;

/** Renomeia as coluna **/
ALTER TABLE TB_TRABALHO RENAME COLUMN id TO TRABALHO_CD;
ALTER TABLE TB_TRABALHO RENAME COLUMN identificacao_da_pessoa_id TO TRABALHO_PESSOA;
ALTER TABLE TB_TRABALHO RENAME COLUMN trabalhou TO TRABALHO_TRABALHOU;
ALTER TABLE TB_TRABALHO RENAME COLUMN afastado TO TRABALHO_AFASTADO;
ALTER TABLE TB_TRABALHO RENAME COLUMN trabalhaAgricultura TO TRABALHO_AGRICULTURA;
ALTER TABLE TB_TRABALHO RENAME COLUMN tipoTrabalho TO TRABALHO_TIPO;
ALTER TABLE TB_TRABALHO RENAME COLUMN remuneracaoMes TO TRABALHO_REMUNERACAO_MES;
ALTER TABLE TB_TRABALHO RENAME COLUMN dozeMeses TO TRABALHO_DOZE_MESES;
ALTER TABLE TB_TRABALHO RENAME COLUMN mesesTrabalhou TO TRABALHO_MESES_TRABALHADOS;
ALTER TABLE TB_TRABALHO RENAME COLUMN remuneracaoAno TO TRABALHO_REMUNERACAO_ANO;
ALTER TABLE TB_TRABALHO RENAME COLUMN tipo_remuneracao_id TO TRABALHO_TP_REMUNERACAO;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TRABALHO ADD COLUMN TRABALHO_CRIADO_EM datetime;
ALTER TABLE TB_TRABALHO ADD COLUMN TRABALHO_ATUALIZADA_EM datetime;
ALTER TABLE TB_TRABALHO ADD COLUMN TRABALHO_DELETADO_EM datetime;
