/** Renomeia a tabela **/
RENAME TABLE tipo_doenca TO TB_TIPO_DOENCA;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_DOENCA RENAME COLUMN tipo_doenca_id TO TP_DOENCA_CD;
ALTER TABLE TB_TIPO_DOENCA RENAME COLUMN descricao TO TP_DOENCA_DESC;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_DOENCA ADD COLUMN TP_DOENCA_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_DOENCA ADD COLUMN TP_DOENCA_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_DOENCA ADD COLUMN TP_DOENCA_DELETADO_EM datetime;
