/** Renomeia a tabela **/
RENAME TABLE tipo_atividade TO TB_TIPO_ATIVIDADE;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_ATIVIDADE RENAME COLUMN tipo_atividade_id TO TP_ATI_CD;
ALTER TABLE TB_TIPO_ATIVIDADE RENAME COLUMN descricao TO TP_ATI_DESCR;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_ATIVIDADE ADD COLUMN TP_ATI_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_ATIVIDADE ADD COLUMN TP_ATI_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_ATIVIDADE ADD COLUMN TP_ATI_DELETADO_EM datetime;
