/** Renomeia a tabela **/
RENAME TABLE tipo_movimentacao_servidor TO TB_TIPO_MOVIMENTACAO_SERVIDOR;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_MOVIMENTACAO_SERVIDOR RENAME COLUMN tipo_matricula_id TO TP_MOV_SERV_CD;
ALTER TABLE TB_TIPO_MOVIMENTACAO_SERVIDOR RENAME COLUMN descricao TO TP_MOV_SERV_DESC;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_MOVIMENTACAO_SERVIDOR ADD COLUMN TP_MOV_SERV_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_MOVIMENTACAO_SERVIDOR ADD COLUMN TP_MOV_SERV_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_MOVIMENTACAO_SERVIDOR ADD COLUMN TP_MOV_SERV_DELETADO_EM datetime;
