/** Renomeia a tabela **/
RENAME TABLE turma_por_docente TO TB_TURMA_DOCENTE;

/** Renomeia as coluna **/
ALTER TABLE TB_TURMA_DOCENTE RENAME COLUMN idturma_por_docente TO TURMA_DOCENTE_CD;
ALTER TABLE TB_TURMA_DOCENTE RENAME COLUMN turma_idturma TO TURMA_DOCENTE_TURMA_CD;
ALTER TABLE TB_TURMA_DOCENTE RENAME COLUMN cadastro_servidor_idcadastro_servidor TO TURMA_DOCENTE_CAD_SERVIDOR_CD;
ALTER TABLE TB_TURMA_DOCENTE RENAME COLUMN docente_iddocente TO TURMA_DOCENTE_DOCENTE_CD;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TURMA_DOCENTE ADD COLUMN TURMA_DOCENTE_CRIADO_EM datetime;
ALTER TABLE TB_TURMA_DOCENTE ADD COLUMN TURMA_DOCENTE_ATUALIZADA_EM datetime;
ALTER TABLE TB_TURMA_DOCENTE ADD COLUMN TURMA_DOCENTE_DELETADO_EM datetime;
