/** Renomeia a tabela **/
RENAME TABLE tipo_matricula TO TB_TIPO_MATRICULA;

/** Renomeia as coluna **/
ALTER TABLE TB_TIPO_MATRICULA RENAME COLUMN tipo_matricula_id TO TP_MATRI_CD;
ALTER TABLE TB_TIPO_MATRICULA RENAME COLUMN descricao TO TP_MATRI_DESC;

/** Adiciona as novas colunas **/
ALTER TABLE TB_TIPO_MATRICULA ADD COLUMN TP_MATRI_CRIADO_EM datetime;
ALTER TABLE TB_TIPO_MATRICULA ADD COLUMN TP_MATRI_ATUALIZADA_EM datetime;
ALTER TABLE TB_TIPO_MATRICULA ADD COLUMN TP_MATRI_DELETADO_EM datetime;
