/** Renomeia a tabela **/
RENAME TABLE users TO TB_USUARIO;

/** Renomeia as coluna **/
ALTER TABLE TB_USUARIO RENAME COLUMN id TO USUARIO_CD;
ALTER TABLE TB_USUARIO RENAME COLUMN username TO USUARIO_USERNAME;
ALTER TABLE TB_USUARIO RENAME COLUMN name TO USUARIO_NAME;
ALTER TABLE TB_USUARIO RENAME COLUMN password TO USUARIO_PASSWORD;
ALTER TABLE TB_USUARIO RENAME COLUMN plainPassword TO USUARIO_PLAIN_PASSWORD;
ALTER TABLE TB_USUARIO RENAME COLUMN email TO USUARIO_EMAIL;
ALTER TABLE TB_USUARIO RENAME COLUMN picture TO USUARIO_PICTURE;
ALTER TABLE TB_USUARIO RENAME COLUMN roles TO USUARIO_ROLES;
ALTER TABLE TB_USUARIO RENAME COLUMN access TO USUARIO_ACCESS;
ALTER TABLE TB_USUARIO RENAME COLUMN gender TO USUARIO_GENDER;
ALTER TABLE TB_USUARIO RENAME COLUMN aluno_id TO USUARIO_ALUNO;
ALTER TABLE TB_USUARIO RENAME COLUMN documento TO USUARIO_DOCUMENTO;
ALTER TABLE TB_USUARIO RENAME COLUMN idFacebook TO USUARIO_FACEBOOK;
ALTER TABLE TB_USUARIO RENAME COLUMN idEstabelecimento TO USUARIO_ESTABELECIMENTO;
ALTER TABLE TB_USUARIO RENAME COLUMN cpf TO USUARIO_CPF;
ALTER TABLE TB_USUARIO RENAME COLUMN token TO USUARIO_TOKEN;
ALTER TABLE TB_USUARIO RENAME COLUMN createdAt TO USUARIO_CRIADO_EM;
ALTER TABLE TB_USUARIO RENAME COLUMN deleted_at TO USUARIO_DELETADO_EM;

/** Adiciona as novas colunas **/
ALTER TABLE TB_USUARIO ADD COLUMN USUARIO_ATUALIZADA_EM datetime;
